### ISSUE TITLE
YAML output includes internal `xxx_*` params

### ISSUE THREAD

**Issue by zoxpx** [portworx/pxc#85]
Using pxc-v0.22.0 -- looks like yaml-outputs always include "garbage"
`xxx_nounkeyedliteral`, `xxx_unrecognized` and `xxx_sizecache` parameters.

UPDATE (Nov-6):
> Looks like YAML-output also produces many more parameters  (likely all the `yaml:"XXX,omitempty"`-ones)]

* JSON output (baseline):
```json
# kubectl pxc get volume -o json
[
  {
    "id": "677916716916499100",
    "source": {},
    "locator": {
      "name": "myvolume"
    },
    "ctime": {
      "seconds": 1573105580,
      "nanos": 29722484
    },
    "spec": {
      "size": 3221225472,
      "format": 2,
      "block_size": 4096,
      "ha_level": 1,
      "cos": 1,
      "aggregation_level": 1,
      "queue_depth": 128,
      "io_strategy": {}
    },
    "last_scan": {
      "seconds": 1573105580,
      "nanos": 29722484
    },
    "format": 2,
    "status": 2,
    "state": 4,
    "attached_state": 2,
    "replica_sets": [
      {
        "nodes": [
          "4b76d807-7924-4fa1-84d0-73af79e31b18"
        ]
      }
    ],
    "runtime_state": [
      {
        "runtime_state": {
          "ID": "0",
          "PXReplReAddNodeMid": "",
          "PXReplReAddPools": "",
          "PXReplicaSet": "[{\"Node\":0,\"NodeId\":\"4b76d807-7924-4fa1-84d0-73af79e31b18\",\"Pool\":0}]",
          "ReplNodePools": "0",
          "ReplRemoveMids": "",
          "ReplicaSetCreateMid": "4b76d807-7924-4fa1-84d0-73af79e31b18",
          "ReplicaSetCurr": "[0]",
          "ReplicaSetCurrMid": "4b76d807-7924-4fa1-84d0-73af79e31b18",
          "RuntimeState": "clean"
        }
      }
    ]
  }
]
```

.. however, corresponding YAML looks like this:

```yaml
# kubectl pxc get volume -o yaml
- id: "677916716916499100"
  source:
    parent: ""
    seed: ""
    xxx_nounkeyedliteral: {}
    xxx_unrecognized: []
    xxx_sizecache: 0
  group: null
  readonly: false
  locator:
    name: myvolume
    volumelabels: {}
    ownership: null
    group: null
    volumeids: []
    xxx_nounkeyedliteral: {}
    xxx_unrecognized: []
    xxx_sizecache: 0
  ctime:
    seconds: 1573105580
    nanos: 29722484
    xxx_nounkeyedliteral: {}
    xxx_unrecognized: []
    xxx_sizecache: 0
  spec:
    ephemeral: false
    size: 3221225472
    format: 2
    blocksize: 4096
    halevel: 1
    cos: 1
    ioprofile: 0
    dedupe: false
    snapshotinterval: 0
    volumelabels: {}
    shared: false
    replicaset: null
    aggregationlevel: 1
    encrypted: false
    passphrase: ""
    snapshotschedule: ""
    scale: 0
    sticky: false
    group: null
    groupenforced: false
    compressed: false
    cascaded: false
    journal: false
    sharedv4: false
    queuedepth: 128
    forceunsupportedfstype: false
    nodiscard: false
    iostrategy:
      asyncio: false
      earlyack: false
      xxx_nounkeyedliteral: {}
      xxx_unrecognized: []
      xxx_sizecache: 0
    placementstrategy: null
    storagepolicy: ""
    ownership: null
    xxx_nounkeyedliteral: {}
    xxx_unrecognized: []
    xxx_sizecache: 0
  usage: 0
  lastscan:
    seconds: 1573105580
    nanos: 29722484
    xxx_nounkeyedliteral: {}
    xxx_unrecognized: []
    xxx_sizecache: 0
  format: 2
  status: 2
  state: 4
  attachedon: ""
  attachedstate: 2
  devicepath: ""
  securedevicepath: ""
  attachpath: []
  attachinfo: {}
  replicasets:
  - nodes:
    - 4b76d807-7924-4fa1-84d0-73af79e31b18
    xxx_nounkeyedliteral: {}
    xxx_unrecognized: []
    xxx_sizecache: 0
  runtimestate:
  - runtimestate:
      ID: "0"
      PXReplReAddNodeMid: ""
      PXReplReAddPools: ""
      PXReplicaSet: '[{"Node":0,"NodeId":"4b76d807-7924-4fa1-84d0-73af79e31b18","Pool":0}]'
      ReplNodePools: "0"
      ReplRemoveMids: ""
      ReplicaSetCreateMid: 4b76d807-7924-4fa1-84d0-73af79e31b18
      ReplicaSetCurr: '[0]'
      ReplicaSetCurrMid: 4b76d807-7924-4fa1-84d0-73af79e31b18
      RuntimeState: clean
    xxx_nounkeyedliteral: {}
    xxx_unrecognized: []
    xxx_sizecache: 0
  error: ""
  volumeconsumers: []
  fsresizerequired: false
  xxx_nounkeyedliteral: {}
  xxx_unrecognized: []
  xxx_sizecache: 0
```
